# Use the official Ubuntu 20.04 base image
FROM ubuntu:20.04

# Set the working directory
WORKDIR /home/cdaron/projects/skyflow/skyflow/slurm/dockerApp

# Copy the Python script into the container
#COPY your_script.py .

# Install any dependencies (if needed)
# For example, you can install Python and its dependencies
# RUN apt-get update && \
#     apt-get install -y python3 && \
#     rm -rf /var/lib/apt/lists/*

# Specify the command to run when the container starts
#CMD ["python", "script.py"]
CMD ["echo", "Hi"]
CMD ["sleep", "100"]
CMD ["echo", "Bye"]
