kind: Service

metadata:
  name: llm-serving-servicedemo

spec:
  type: LoadBalancer
  # Enter which cluster to deploy service on.
  # By default, it selects the cluster with most replicas.
  primary_cluster: remote
  selector:
    app: llm-serving
  ports:
    - protocol: TCP
      port: 8080
      target_port: 28000
