kind: Service

metadata:
  name: productpage

spec:
  type: LoadBalancer
  # Enter which cluster to deploy service on.
  # By default, it selects the cluster with most replicas.
  primary_cluster: kind-cluster1
  selector:
    app: productpage
  ports:
    - protocol: TCP
      port: 80
      target_port: 9080
