name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-and-test:
    runs-on: self-hosted
    # outputs:
    #   runCmdOutput: ${{ steps.devc.outputs.runCmdOutput }}
    steps:
      - uses: actions/checkout@v4
      - name: Build dev container and run tests
        # id: devc
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            echo "CID=$HOSTNAME" >> $GITHUB_ENV
            pip install -e .[server,dev]
            minikube start
            pytest skyflow/tests

  cleanup:
    needs: build-and-test
    runs-on: self-hosted
    if: always()
    steps:
      - name: Delete checked-out repository
        run: |
          # docker rm -f ${{ needs.build-and-test.outputs.runCmdOutput }}
          docker rm -f $CID
      - name: Delete checked-out repository
        run: |
          rm -rf $GITHUB_WORKSPACE