name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: setup.py
      - name: Install Dependencies
        run: pip install -e .[server,dev]
      # - name: Check Format and Lint
      #   run: bash format.sh --all --check
      - name: Run Tests
        run: pytest skyflow/tests -k "test_filter_with_match_expression"
      - name: Echo API Logs
        if: always()
        run: cat /tmp/api.log
      - name: Echo Manager Logs
        if: always()
        run: cat ~/.skyconf/*
