name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  format-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.head_ref }}
            fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
            python-version: '3.10' 

      - name: Install project in editable mode with extras
        run: |
              python -m pip install --upgrade pip
              pip install -e .[server,dev]
        
      - name: Check format
        run: |
              chmod +x ./format.sh
              ./format.sh
      
      - name: Run tests with pytest
        run: |
              pytest ./skyflow/tests

      - name: Commit and push changes if tests pass
        run: |
              git config --global user.name 'Huanzhi Mao'
              git config --global user.email 'huanzhimao@gmail.com'
              git add .
              git diff --staged --quiet || git commit -m "Github Action Bot Apply Code Formatting"
              git push
