name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-and-test:
    runs-on: self-hosted
    # container: ubuntu:24.04
    steps:
      - uses: actions/checkout@v4
      # - name: Install Python
      #   run: apt update && apt install -y python3 python3-pip
      # - name: Install dependencies
      #   run: pip install -e .[server,dev]
      # - name: Run tests
      #   run: pytest skyflow/tests
      - name: Pre-build image and run make ci-build in dev container
        uses: devcontainers/ci@v0.3
        with:
          # noCache: true
          runCmd: echo $HOSTNAME && pip install -e .[server,dev] && minikube start && pytest skyflow/tests

  cleanup:
    needs: build-and-test
    runs-on: self-hosted
    if: always()
    steps:
      - name: Delete checked-out repository
        run: |
          rm -rf $GITHUB_WORKSPACE