name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Pre-build image and run make ci-build in dev container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: pip install -e .[server,dev] && minikube start && pytest skyflow/tests

  cleanup:
    needs: build-and-test
    runs-on: self-hosted
    if: always()
    steps:
      - name: Delete checked-out repository
        run: |
          rm -rf $GITHUB_WORKSPACE