name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Build Docker Image
        run: docker build -t skyflow:cicd_test .

      - name: Install Kind
        run: |
          [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64 && \
          chmod +x ./kind && \
          sudo mv ./kind /usr/local/bin/kind && \
          kind --version

      - name: Create Kubernetes Cluster
        run: kind create cluster

      # Run Tests inside Docker Container
      - name: Run tests in Docker
        run: docker run --name SkyflowTestContainer skyflow:cicd_test pytest ./skyflow/tests/test_etcd_client.py

      - name: Remove test container
        if: always()
        run: docker rm SkyflowTestContainer || true

      - name: Commit and push changes
        run: |
          chmod +x ./format.sh
          ./format.sh
          git config --global user.name 'Huanzhi Mao'
          git config --global user.email 'huanzhimao@gmail.com'
          git add .
          git diff --staged --quiet || git commit -m "Github Action Bot Apply Code Formatting"
          git push
