name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # - name: Build Docker Image
      #   run: docker build -t skyflow:cicd_test .
      
      # - name: Set up Python 3.10
      #   run: |
      #     sudo apt update
      #     sudo apt upgrade -y
      #     sudo apt install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev curl libbz2-dev libsqlite3-dev
      #     curl -O https://www.python.org/ftp/python/3.10.14/Python-3.10.14.tar.xz
      #     tar -xf Python-3.10.14.tar.xz
      #     cd Python-3.10.14
      #     ./configure --enable-optimizations
      #     make -j `nproc`
      #     sudo make altinstall
      #     python3.10 --version


      - name: Install dependencies
        run: pip install --no-cache-dir -e .[server,dev]

      # - name: Install kind
      #   uses: helm/kind-action@v1.9.0
      #   with:
      #     install_only: true
      # - name: Install Kind
      #   run: |
      #     [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64 && \
      #     chmod +x ./kind && \
      #     sudo mv ./kind /usr/local/bin/kind && \
      #     kind --version

      # - uses: azure/setup-kubectl@v3
      #   with:
      #     version: 'latest'
      #   id: install

      # - name: Create Kubernetes Cluster
      #   run: kind create cluster || true

      # Run Tests inside Docker Container
      - name: Run tests
        run: pytest ./skyflow/tests/test_clusterlink.py 

      # - name: Commit and push changes
      #   run: |
      #     chmod +x ./format.sh
      #     ./format.sh
      #     git config --global user.name 'Huanzhi Mao'
      #     git config --global user.email 'huanzhimao@gmail.com'
      #     git add .
      #     git diff --staged --quiet || git commit -m "Github Action Bot Apply Code Formatting"
      #     git push
