name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-and-test:
    runs-on: self-hosted
    outputs:
      containerId: ${{ steps.devcontainer.outputs.containerId }}
    steps:
      - uses: actions/checkout@v4
      - id: devcontainer
        name: Build dev container and run tests
        uses: devcontainers/ci@v0.3
        with:
          noCache: True
          runCmd: |
            echo "containerId=$HOSTNAME" >> "$GITHUB_OUTPUT"
            go install sigs.k8s.io/kind@v0.22.0 && kind create cluster
            pip install -e .[server,dev]
            minikube start
            pytest skyflow/tests

  cleanup:
    needs: build-and-test
    runs-on: self-hosted
    if: always()
    steps:
      - name: Delete docker container
        run: docker rm -f ${{ needs.build-and-test.outputs.containerId }}
      - name: Delete checked-out repository
        run: rm -rf $GITHUB_WORKSPACE
