name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # - name: Build Docker Image
      #   run: docker build -t skyflow:cicd_test .
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: RUN pip install --upgrade pip && pip install --no-cache-dir -e .[server,dev]

      - name: Install kind
        uses: helm/kind-action@v1.9.0
        with:
          install_only: true
      # - name: Install Kind
      #   run: |
      #     [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64 && \
      #     chmod +x ./kind && \
      #     sudo mv ./kind /usr/local/bin/kind && \
      #     kind --version

      - uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
        id: install

      # - name: Create Kubernetes Cluster
      #   run: kind create cluster || true

      # Run Tests inside Docker Container
      - name: Run tests
        run: pytest ./skyflow/tests/test_clusterlink.py 

      # - name: Commit and push changes
      #   run: |
      #     chmod +x ./format.sh
      #     ./format.sh
      #     git config --global user.name 'Huanzhi Mao'
      #     git config --global user.email 'huanzhimao@gmail.com'
      #     git add .
      #     git diff --staged --quiet || git commit -m "Github Action Bot Apply Code Formatting"
      #     git push
