name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main  # or your default branch

# Give the workflow permission to push to gh-pages
permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          # If you have a requirements file for docs:
          pip install -r docs/requirements-docs.txt
          # Otherwise, just install Sphinx:
          # pip install sphinx

      - name: Build docs
        # This runs your build.sh inside docs/
        working-directory: docs
        run: |
          bash build.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # By default, it will push to gh-pages branch, but being explicit doesn't hurt:
          publish_branch: gh-pages
          # Adjust the path if your Sphinx output differs
          publish_dir: docs/build/html
          # If your docs build is at docs/build/html, *relative to repository root*,
          # then keep the above. If your 'build.sh' is set up differently, adjust as needed.
