name: Build and Deploy to sky-shift.github.io

on:
  push:
    branches:
      - main  # or whichever branch you use

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out skyshift repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          # e.g., if you have a docs requirements file:
          pip install -r docs/requirements-docs.txt
          # or if you have a setup.py/pyproject:
          # pip install -e .

      - name: Build your docs/site
        working-directory: docs  # or wherever your build script is
        run: |
          # For Sphinx with a makefile:
          # make html
          #
          # or if you have a custom script:
          bash build.sh

      - name: Deploy to sky-shift.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Use your PAT secret here (NOT the default GITHUB_TOKEN)
          #github_token: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
          personal_token: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}  # <-- Use personal_token here

          # This is the external repo to push to
          external_repository: sky-shift/sky-shift.github.io

          # The branch in sky-shift.github.io where you want final files
          # Usually "main" or "master" for a user/organization site
          publish_branch: main

          # The folder with the built HTML (relative to the *skyshift* repo root)
          publish_dir: docs/build/html

          # (Optional) Customize commit author
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
